"""Add relationship between User and Book

Revision ID: e145c6a0a3ba
Revises: 9a45bdb933bc
Create Date: 2025-01-07 16:31:44.781148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e145c6a0a3ba'
down_revision = '9a45bdb933bc'
branch_labels = None
depends_on = None


def upgrade():
    # Remove this line
    op.drop_table('_alembic_tmp_books')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_user_book', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_book', type_='foreignkey')  # Specify the name of the constraint
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_books',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=255), nullable=False),
        sa.Column('author', sa.VARCHAR(length=255), nullable=False),
        sa.Column('cover_image', sa.VARCHAR(length=255), nullable=True),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('genre', sa.VARCHAR(length=100), nullable=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_book'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
